spring:
  application:
    name: pawkey-dev

  datasource:
    url: "jdbc:postgresql://pawkey-dev.cl0m2u2y2v1m.ap-northeast-2.rds.amazonaws.com:5432/pawkey-dev"
    username: postgres
    password: Pawkeymooserver36!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false